global:
  name: consul
  datacenter: dc2
  logLevel: "debug"
  tls:
    enabled: true

    # Here we're using the shared certificate authority from the primary
    # datacenter that was exported via the federation secret.
    caCert:
      secretName: consul-federation
      secretKey: caCert
    caKey:
      secretName: consul-federation
      secretKey: caKey

  federation:
    enabled: true
    k8sAuthMethodHost: https://2B5DDF5F6FA68D565743A11E34205A07.gr7.eu-west-1.eks.amazonaws.com
    primaryDatacenter: dc1
  # gossipEncryption:
  #   secretName: consul-federation
  #   secretKey: gossipEncryptionKey
connectInject:
  enabled: true
meshGateway:
  enabled: true
server:
  # Here we're including the server config exported from the primary
  # via the federation secret. This config includes the addresses of
  # the primary datacenter's mesh gateways so Consul can begin federation.
  extraVolumes:
    - type: secret
      name: consul-federation
      items:
        - key: serverConfigJSON
          path: config.json
      load: true
